name: action-slack - workflow status notifications in slack
description: Sends slack notifications about the status of a workflow
author: titenkov
branding:
  icon: bell
  color: yellow
inputs:
  status:
    description: Job Status
    required: true
  title:
    description: Title
    required: false
    default: ''
  text:
    description: Text
    required: false
    default: ''
  compact:
    description: Compact mode
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'index.js'
