name: CI
on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v5

      - name: 🎉 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: ./
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
